# Generated by Django 2.1.1 on 2018-09-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_rating', models.CharField(max_length=200)),
                ('food_rating', models.CharField(max_length=200)),
                ('atmosphere_rating', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('logged_in', models.DateTimeField()),
            ],
        ),
    ]
